<?php

/**
 * @file
 * LocalGov Subsites install file.
 */

/**
 * Implements hook_install().
 */
function localgov_subsites_install($is_syncing) {
  if ($is_syncing) {
    return;
  }

  if (\Drupal::moduleHandler()->moduleExists('localgov_services_navigation')) {
    localgov_subsites_optional_fields_settings();
  }

  // Install default config for simple_sitemap, as this does not appear to work
  // in the config/optional folder.
  // Discussed on https://www.drupal.org/project/simple_sitemap/issues/3156080
  if (\Drupal::moduleHandler()->moduleExists('simple_sitemap')) {
    $generator = \Drupal::service('simple_sitemap.entity_manager');
    $generator->setBundleSettings('node', 'localgov_subsites_overview', [
      'index' => TRUE,
      'priority' => '1.0', // Cast as string to ensure the value is properly set
    ]);
    $generator->setBundleSettings('node', 'localgov_subsites_page', [
      'index' => TRUE,
      'priority' => '0.5',
    ]);
  }
}

/**
 * Clear caches after moving subsites paragraphs to localgov_paragraphs.
 */
function localgov_subsites_update_9001() {

  drupal_flush_all_caches();
}
