<?php

/**
 * @file
 * LocalGov Subsites install file.
 */

/**
 * Implements hook_install().
 */
function localgov_subsites_install($is_syncing) {
  if ($is_syncing) {
    return;
  }

  if (\Drupal::moduleHandler()->moduleExists('localgov_services_navigation')) {
    localgov_subsites_optional_fields_settings();
  }
}

/**
 * Clear caches after moving subsites paragraphs to localgov_paragraphs.
 */
function localgov_subsites_update_9001() {

  drupal_flush_all_caches();
}
