<?php

/**
 * @file
 * LocalGov Subsites module file.
 */

use Drupal\localgov_roles\RolesHelper;
use Drupal\localgov_subsites\Subsite;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function localgov_subsites_theme($existing, $type, $theme, $path) {
  return [
    'subsite_navigation' => [
      'variables' => [
        'menu_name' => '',
        'items' => [],
        'current_entity' => NULL,
        'overview_entity' => NULL,
      ],
    ],
    'subsite_banner' => [
      'variables' => [
        'tag' => '',
        'heading' => '',
        'image' => '',
      ],
    ],
    'node__localgov_subsites_page__full' => [
      'template' => 'node--localgov-subsites-page--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_localgov_role_default().
 */
function localgov_subsites_localgov_roles_default() {

  // Content editing permissions.
  $perms = [
    RolesHelper::EDITOR_ROLE => [
      'create localgov_subsites_overview content',
      'create localgov_subsites_page content',
      'delete any localgov_subsites_overview content',
      'delete any localgov_subsites_page content',
      'delete localgov_subsites_overview revisions',
      'delete localgov_subsites_page revisions',
      'delete own localgov_subsites_overview content',
      'delete own localgov_subsites_page content',
      'edit any localgov_subsites_overview content',
      'edit any localgov_subsites_page content',
      'edit own localgov_subsites_overview content',
      'edit own localgov_subsites_page content',
      'revert localgov_subsites_overview revisions',
      'revert localgov_subsites_page revisions',
      'view localgov_subsites_overview revisions',
      'view localgov_subsites_page revisions',
    ],
    RolesHelper::AUTHOR_ROLE => [
      'create localgov_subsites_overview content',
      'create localgov_subsites_page content',
      'delete own localgov_subsites_overview content',
      'delete own localgov_subsites_page content',
      'edit own localgov_subsites_overview content',
      'edit own localgov_subsites_page content',
      'revert localgov_subsites_overview revisions',
      'revert localgov_subsites_page revisions',
      'view localgov_subsites_overview revisions',
      'view localgov_subsites_page revisions',
    ],
    RolesHelper::CONTRIBUTOR_ROLE => [
      'create localgov_subsites_overview content',
      'create localgov_subsites_page content',
      'delete own localgov_subsites_overview content',
      'delete own localgov_subsites_page content',
      'edit own localgov_subsites_overview content',
      'edit own localgov_subsites_page content',
      'view localgov_subsites_overview revisions',
      'view localgov_subsites_page revisions',
    ],
  ];

  // Content scheduling permissions required by localgov_workflows.
  if (\Drupal::moduleHandler()->moduleExists('localgov_workflows')) {
    $perms[RolesHelper::EDITOR_ROLE] = array_merge($perms[RolesHelper::EDITOR_ROLE], [
      'add scheduled transitions node localgov_subsites_overview',
      'add scheduled transitions node localgov_subsites_page',
      'reschedule scheduled transitions node localgov_subsites_overview',
      'reschedule scheduled transitions node localgov_subsites_page',
      'view scheduled transitions node localgov_subsites_overview',
      'view scheduled transitions node localgov_subsites_page',
    ]);
    $perms[RolesHelper::AUTHOR_ROLE] = array_merge($perms[RolesHelper::AUTHOR_ROLE], [
      'add scheduled transitions node localgov_subsites_overview',
      'add scheduled transitions node localgov_subsites_page',
      'reschedule scheduled transitions node localgov_subsites_overview',
      'reschedule scheduled transitions node localgov_subsites_page',
      'view scheduled transitions node localgov_subsites_overview',
      'view scheduled transitions node localgov_subsites_page',
    ]);
    $perms[RolesHelper::CONTRIBUTOR_ROLE] = array_merge($perms[RolesHelper::CONTRIBUTOR_ROLE], [
      'add scheduled transitions node localgov_subsites_overview',
      'add scheduled transitions node localgov_subsites_page',
      'reschedule scheduled transitions node localgov_subsites_overview',
      'reschedule scheduled transitions node localgov_subsites_page',
      'view scheduled transitions node localgov_subsites_overview',
      'view scheduled transitions node localgov_subsites_page',
    ]);
  }

  return $perms;
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds a class to the page wrapper with the name of the theme
 * if the current node is within a subsite.
 */
function localgov_subsites_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node instanceof NodeInterface) {
    return;
  }

  if (in_array($node->bundle(), [
    'localgov_subsites_overview',
    'localgov_subsites_page',
  ])) {
    $subsite = \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(Subsite::class)
      ->getSubsite($node);

    if ($subsite instanceof NodeInterface && $theme = $subsite->localgov_subsites_theme->value) {
      $variables['attributes']['class'][] = str_replace('_', '--', $theme);
    }
  }
}
