<?php

/**
 * @file
 * LocalGov Campaigns module file.
 */

/**
 * Implements hook_theme().
 */
function localgov_campaigns_theme($existing, $type, $theme, $path) {
  return [
    'campaign_navigation' => [
      'variables' => [
        'heading' => '',
        'links' => [],
        'parent_url' => '',
      ],
    ],
    'campaign_banner' => [
      'variables' => [
        'tag' => '',
        'heading' => '',
        'image' => '',
      ],
    ],
    'campaign_overview_banner' => [
      'variables' => [
        'heading' => '',
        'image' => '',
      ],
    ],
    'node__localgov_campaigns_page__full' => [
      'template' => 'node--localgov-campaigns-page--full',
      'base hook' => 'node',
    ],
  ];
}
