<?php

/**
 * @file
 * LocalGov Campaigns module file.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function localgov_campaigns_theme($existing, $type, $theme, $path) {
  return [
    'campaign_navigation' => [
      'variables' => [
        'heading' => '',
        'links' => [],
        'parent_url' => '',
      ],
    ],
    'campaign_banner' => [
      'variables' => [
        'tag' => '',
        'heading' => '',
        'image' => '',
      ],
    ],
    'campaign_overview_banner' => [
      'variables' => [
        'heading' => '',
        'image' => '',
      ],
    ],
    'node__localgov_campaigns_page__full' => [
      'template' => 'node--localgov-campaigns-page--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function localgov_campaigns_node_insert(NodeInterface $node) {
  localgov_campaigns_node_update($node);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Implements reference back on overview to page when pages are created.
 */
function localgov_campaigns_node_update(NodeInterface $node) {
  if ($node->bundle() == 'localgov_campaigns_page') {
    if ($parent = $node->localgov_campaigns_parent->entity) {
      // Check if referenced campaign has changed.
      if (isset($node->original) and $old_parent = $node->original->localgov_campaigns_parent->entity) {
        if ($old_parent->id() !== $parent->id()) {
          $i = array_search(['target_id' => $node->id()], $old_parent->localgov_campaigns_pages->getValue());
          if ($i !== FALSE) {
            $old_parent->localgov_campaigns_pages->removeItem($i);
            $old_parent->save();
          }
        }
      }
      // Add page to parent reference field.
      elseif (array_search(['target_id' => $node->id()], $parent->localgov_campaigns_pages->getValue()) === FALSE) {
        $parent->localgov_campaigns_pages->appendItem(['target_id' => $node->id()]);
        $parent->save();
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function localgov_campaigns_node_delete(NodeInterface $node) {
  if ($node->bundle() == 'localgov_campaigns_page') {
    if ($parent = $node->localgov_campaigns_parent->entity) {
      $i = array_search(['target_id' => $node->id()], $parent->localgov_campaigns_pages->getValue());
      if ($i !== FALSE) {
        $parent->localgov_campaigns_pages->removeItem($i);
        $parent->save();
      }
    }
  }
}
