<?php

/**
 * @file
 * LocalGovDrupal Campaigns Paragraphs module file.
 */

use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_theme().
 */
function localgov_campaigns_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__box_link' => [
      'template' => 'paragraph--box-link',
      'base hook' => 'paragraph',
    ],
    'paragraph__call_out_box' => [
      'template' => 'paragraph--call-out-box',
      'base hook' => 'paragraph',
    ],
    'paragraph__fact_box' => [
      'template' => 'paragraph--fact-box',
      'base hook' => 'paragraph',
    ],
    'paragraph__link_and_summary' => [
      'template' => 'paragraph--link-and-summary',
      'base hook' => 'paragraph',
    ],
    'paragraph__quote' => [
      'template' => 'paragraph--quote',
      'base hook' => 'paragraph',
    ],
    'paragraph__text' => [
      'template' => 'paragraph--text',
      'base hook' => 'paragraph',
    ],
    'paragraph__text_and_image_50_50' => [
      'template' => 'paragraph--text-and-image-50-50',
      'base hook' => 'paragraph',
    ],
    'paragraph__video_page_builder' => [
      'template' => 'paragraph--video-page-builder',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_campaigns_paragraphs_preprocess_paragraph(&$variables) {
  $variables['#attached']['library'][] = 'localgov_campaigns_paragraphs/localgov_campaigns_paragraphs';

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->bundle() === 'box_link') {
    if (!$paragraph->get('field_link')->isEmpty()) {
      $link = $paragraph->get('field_link')->first()->getValue();
      $variables['field_link']['title'] = $link['title'];
      $variables['field_link']['url'] = Url::fromUri($link['uri']);
    }
  }

  if ($paragraph->bundle() === 'call_out_box') {
    if (!$paragraph->get('field_button')->isEmpty()) {
      $button = $paragraph->get('field_button')->first()->getValue();
      $variables['button_url'] = Url::fromUri($button['uri']);
    }
    if (!$paragraph->get('field_background_image')->isEmpty()) {
      $image_uri = $paragraph->get('field_background_image')->entity->getFileUri();
      $variables['background_url'] = ImageStyle::load('large_21_9')->buildUrl($image_uri);
    }
  }

  if ($paragraph->bundle() === 'video_page_builder') {
    if (!$paragraph->get('field_video_url')->isEmpty()) {
      $video = $paragraph->get('field_video_url')->first()->getValue();
      $variables['field_video_url'] = $video['uri'];
    }
  }
}
